name: DemoPipeline

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Notify Pipeline Started
        run: |
          curl -X POST https://zwd5dhzokcmnswk3ih3hxxa6240wqwmc.lambda-url.us-east-1.on.aws/ \
            -H "Content-Type: application/json" \
            -d '{"pipeline":"DemoPipeline","execution_id":"${{ github.run_id }}","state":"STARTED","commit_message":"${{ github.event.head_commit.message }}","author":"${{ github.actor }}"}'

      - name: Execute Build & Test
        run: |
          echo "Simulating CI/CD automated tests..."
         
          exit 0

      - name: Notify Pipeline Succeeded
        if: success()
        run: |
          curl -X POST https://zwd5dhzokcmnswk3ih3hxxa6240wqwmc.lambda-url.us-east-1.on.aws/ \
            -H "Content-Type: application/json" \
            -d '{"pipeline":"DemoPipeline","execution_id":"${{ github.run_id }}","state":"SUCCEEDED","commit_message":"${{ github.event.head_commit.message }}","author":"${{ github.actor }}"}'

      - name: Notify Pipeline Failed
        if: failure()
        run: |
          curl -X POST https://zwd5dhzokcmnswk3ih3hxxa6240wqwmc.lambda-url.us-east-1.on.aws/ \
            -H "Content-Type: application/json" \
            -d '{"pipeline":"DemoPipeline","execution_id":"${{ github.run_id }}","state":"FAILED","commit_message":"${{ github.event.head_commit.message }}","author":"${{ github.actor }}"}'
